/* لعبك — party games engine
   Front-end demo only. Never treat localStorage/sessionStorage as authentication or payment security.
*/
const KEY="la3bak_games_v4";
const games=[
{id:"spy",name:"مين الجاسوس؟",desc:"كل اللاعبين يعرفون الكلمة ما عدا الجاسوس. أعطوا تلميحات ذكية ثم صوّتوا.",price:9,players:"3–8",emoji:"🕵️",type:"red",time:"10–15 دقيقة",rules:["أدخلوا أسماء اللاعبين.","كل لاعب يرى دوره سرًا: مواطن أو جاسوس.","المواطنون يعرفون الكلمة، والجاسوس يعرف التصنيف فقط.","كل لاعب يعطي تلميحًا قصيرًا دون كشف الكلمة.","بعد النقاش يصوّت الجميع على الجاسوس.","إذا انكشف الجاسوس، يحصل على فرصة أخيرة لتخمين الكلمة."]},
{id:"draw",name:"ارسم وخمّن",desc:"واحد يرسم والباقون يتسابقون في التخمين قبل انتهاء الوقت.",price:9,players:"3–10",emoji:"🎨",type:"purple",time:"10–20 دقيقة",rules:["يختار النظام كلمة سرية للرسام.","لدى الرسام 60 ثانية للرسم.","الممنوع: كتابة حروف أو أرقام داخل الرسم.","الباقون يرسلون تخميناتهم شفهيًا أو على نفس الجهاز.","كلما كان التخمين أسرع زادت النقاط."]},
{id:"yesno",name:"لا تقول نعم ولا لا",desc:"أسئلة سريعة وفخاخ ذكية. حافظ على أعصابك ولا تنطق الكلمتين الممنوعتين.",price:9,players:"3–10",emoji:"🚫",type:"blue",time:"8–15 دقيقة",rules:["اختاروا لاعبًا ليكون الهدف في الجولة.","يطرح اللاعبون أسئلة سريعة عليه.","الكلمتان الممنوعتان: نعم ولا.","يمكن استخدام إجابات مثل: أكيد، أبدًا، ممكن، صحيح.","إذا قال الهدف كلمة ممنوعة تنتهي الجولة فورًا."]},
{id:"trivia",name:"تحدي المعلومات",desc:"أسئلة متنوعة، وقت محدود، ونقاط أكثر للإجابة الصحيحة بسرعة.",price:9,players:"2–10",emoji:"🧠",type:"green",time:"8–12 دقيقة",rules:["كل سؤال يظهر بأربع إجابات.","اختار إجابة قبل انتهاء العداد.","الإجابة الصحيحة تمنح نقاطًا.","السرعة تمنحك نقاطًا إضافية.","بعد آخر سؤال يظهر الترتيب والفائز."]},
{id:"would",name:"لو خيروك",desc:"اختيارات مستحيلة وتصويت يكشف من يفكر مثلك ومن يخالفك.",price:9,players:"3–12",emoji:"⚡",type:"purple",time:"10–15 دقيقة",rules:["يظهر سؤال بخيارين.","كل لاعب يختار سرًا A أو B.","بعد الإغلاق تظهر النتيجة ونسبة التصويت.","يمكنكم إعطاء نقطة لمن اختار الأقلية إذا أردتم نمط التحدي.","الفائز هو صاحب أعلى نقاط في نهاية الجولات."]},
{id:"charades",name:"تمثّلها!",desc:"مثّل الكلمة بدون كلام، وأصحابك يحاولون معرفة ما تمثله قبل انتهاء الوقت.",price:9,players:"3–10",emoji:"🎭",type:"red",time:"10–20 دقيقة",rules:["يظهر للاعب الممثل موضوع سري.","لديه 60 ثانية للتمثيل بدون كلام.","الممنوع قول الكلمة أو تهجئتها.","إذا عرفها الفريق قبل الوقت يحصلون على نقطة.","بدّلوا الممثل كل جولة."]}
];
const words={draw:["بيتزا","مظلة","قطة","طائرة","بركان","دراجة","روبوت","شاطئ","نظارة","هاتف","صاروخ","بطاطس","أسد","مدرسة","ساعة"],charades:["يطبخ","يسوق","ينام","يرقص","يصطاد","يلعب كرة","يصور سيلفي","يبحث عن مفتاح","يتزلج","يفتح هدية","يخاف من فأر","يشرب قهوة"]};
const trivia=[
["ما عاصمة السعودية؟",["الرياض","جدة","الدمام","أبها"],0],
["كم عدد أيام الأسبوع؟",["5","6","7","8"],2],
["أي كوكب يُعرف بالكوكب الأحمر؟",["الزهرة","المريخ","المشتري","عطارد"],1],
["كم دقيقة في الساعة؟",["30","45","60","90"],2],
["ما أكبر محيط على الأرض؟",["الأطلسي","الهندي","الهادئ","المتجمد الشمالي"],2],
["أي حيوان يُعرف بسفينة الصحراء؟",["الحصان","الجمل","الفيل","الذئب"],1],
["كم ضلعًا للمثلث؟",["2","3","4","5"],1],
["ما الغاز الذي يحتاجه الإنسان للتنفس؟",["الأكسجين","الهيليوم","الهيدروجين","النيتروجين فقط"],0]
];
const spyWords=[
["أكلات","كبسة"],["حيوانات","بطريق"],["أماكن","مطار"],["رياضة","كرة قدم"],["أشياء يومية","مفتاح"],["مشروبات","قهوة"],["تقنية","هاتف"],["مهن","طبيب"],["سيارات","سيارة سباق"],["طبيعة","شلال"]
];
const would=["تعيش سنة بدون جوال 📵 أم سنة بدون سفر ✈️؟","تأكل نفس الوجبة شهرًا 🍔 أم لا تأكلها أبدًا؟","تكون سريعًا جدًا 🏃 أم قويًا جدًا 💪؟","تملك وقتًا أكثر ⏰ أم مالًا أكثر 💰؟","تسافر للمستقبل 🚀 أم للماضي 🕰️؟","تضحك في كل موقف 😂 أم لا تضحك أبدًا؟"];

/* أكواد مجانية - نسخة تجريبية محلية. في الإنتاج يجب نقل التحقق إلى الخادم/قاعدة البيانات. */
const FREE_CODES={
  "L3BAK-FREE-2026":{label:"كود تجريبي شامل",gameId:"*",maxUses:999999,expires:"2026-12-31"},
  "L3BAK-SPY-2026":{label:"مين الجاسوس؟",gameId:"spy",maxUses:100,expires:"2026-12-31"}
};
function normalizeCode(v){return String(v||"").trim().toUpperCase().replace(/\s+/g,"").slice(0,40)}
function getCodeState(){const d=getData();d.redeemedCodes=d.redeemedCodes||{};return d}
function validFreeCode(code,gameId){const c=FREE_CODES[normalizeCode(code)];if(!c)return {ok:false,msg:"الكود غير صحيح ❌"};if(c.expires && new Date(c.expires+"T23:59:59")<new Date())return {ok:false,msg:"انتهت صلاحية هذا الكود ⏰"};if(c.gameId!=="*"&&c.gameId!==gameId)return {ok:false,msg:"هذا الكود مخصص للعبة أخرى 🎮"};const d=getCodeState(),used=Number(d.redeemedCodes[normalizeCode(code)]||0);if(used>=c.maxUses)return {ok:false,msg:"تم استخدام الكود الحد الأقصى من المرات"};return {ok:true,code:normalizeCode(code),info:c,used};}
function redeemFreeCode(gameId){const input=document.getElementById("freeCodeInput"),msg=document.getElementById("freeCodeMsg");const code=normalizeCode(input?.value);const result=validFreeCode(code,gameId);if(!result.ok){if(msg)msg.textContent=result.msg;return false}const d=getCodeState();d.redeemedCodes[code]=Number(d.redeemedCodes[code]||0)+1;d.freeEntitlements=d.freeEntitlements||{};d.freeEntitlements[gameId]={code,at:Date.now()};saveData(d);if(msg)msg.textContent="تم تفعيل الكود ✅ يمكنك بدء اللعبة مجانًا";return true}
function hasFreeEntitlement(gameId){const d=getData(),e=d.freeEntitlements?.[gameId];return !!(e&&e.code&&FREE_CODES[e.code]&&validFreeCode(e.code,gameId).ok)}
function getData(){try{return JSON.parse(localStorage.getItem(KEY))||{rooms:[],orders:[]}}catch{return {rooms:[],orders:[]}}}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function id(){try{return crypto.randomUUID()}catch{return Date.now().toString(36)+Math.random().toString(36).slice(2)}}
function roomCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let out="";if(crypto?.getRandomValues){const a=new Uint32Array(6);crypto.getRandomValues(a);for(let i=0;i<6;i++)out+=chars[a[i]%chars.length]}else for(let i=0;i<6;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function getGame(gid){return games.find(g=>g.id===gid)||games[0]}
function renderGames(){const el=document.getElementById("gamesGrid");if(!el)return;const q=(document.getElementById("gameSearch")?.value||"").trim().toLowerCase();const list=games.filter(g=>(g.name+g.desc).toLowerCase().includes(q));el.innerHTML=list.map(g=>`<article class="game-card"><div class="cover ${g.type}">${g.emoji}</div><div class="game-info"><h3>${esc(g.name)}</h3><p>${esc(g.desc)}</p><div class="game-meta"><span>👥 ${esc(g.players)}</span><strong>${g.price} ريال</strong></div><a class="btn" href="game.html?id=${encodeURIComponent(g.id)}">شرح اللعبة والبدء <span>←</span></a></div></article>`).join("")}
function filterGames(){renderGames()}
function toggleMenu(){document.getElementById("mobileMenu")?.classList.toggle("hidden")}
function renderGame(){const el=document.getElementById("gamePage");if(!el)return;const idq=new URLSearchParams(location.search).get("id")||"spy";const g=getGame(idq);el.innerHTML=`<section class="game-detail-head"><div class="detail-cover ${g.type}">${g.emoji}<span>${esc(g.name)}</span></div><div class="detail-copy"><span class="pill">🎮 لعبة جماعية</span><h1>${esc(g.name)}</h1><p class="lead">${esc(g.desc)}</p><div class="stats"><span>👥 ${esc(g.players)}</span><span>⏱ ${esc(g.time)}</span><span>⭐ ممتعة وسريعة</span></div><div class="free-code-box"><div><b>🎁 عندك كود مجاني؟</b><small>أدخل الكود الذي أعطاك إياه صاحب الموقع لفتح اللعبة مجانًا.</small></div><div class="code-row"><input id="freeCodeInput" maxlength="40" autocomplete="off" placeholder="مثال: L3BAK-FREE-2026"><button class="btn" onclick="redeemFreeCode('${g.id}')">تفعيل الكود</button></div><p id="freeCodeMsg" class="code-msg"></p></div><button class="btn primary big" onclick="createRoom('${g.id}')">أنشئ غرفة والعب الآن 🚀</button></div></section><section class="rules-card"><div><span class="eyebrow">شرح اللعبة</span><h2>كيف تلعب؟</h2></div><div class="rules-list">${g.rules.map((r,i)=>`<div><b>${i+1}</b><p>${esc(r)}</p></div>`).join("")}</div><div class="safety-note">🔒 <b>الحماية:</b> نظام الكود هنا نسخة تجريبية على المتصفح. لا نعتبره حماية تجارية حقيقية حتى نربطه بقاعدة بيانات وخادم.</div></section>`}
function createRoom(gameId){const g=getGame(gameId);const input=document.getElementById("freeCodeInput");const entered=normalizeCode(input?.value);const entitlement=getData().freeEntitlements?.[gameId];if(entered&&(!entitlement||entitlement.code!==entered)){if(!redeemFreeCode(gameId))return}const d=getData(),code=roomCode();const room={code,gameId,host:id(),players:[],createdAt:Date.now(),phase:"lobby",scores:{},state:{},access:hasFreeEntitlement(gameId)?"free-code":"demo"};room.players.push({id:room.host,name:"المضيف",host:true});d.rooms.push(room);saveData(d);location.href=`room.html?code=${encodeURIComponent(code)}`}
function loadRoom(){const code=(new URLSearchParams(location.search).get("code")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8);const d=getData();return d.rooms.find(r=>r.code===code)||null}
function updateRoom(room){const d=getData(),i=d.rooms.findIndex(r=>r.code===room.code);if(i>=0){d.rooms[i]=room;saveData(d)}return room}
function renderRoom(){const room=loadRoom();const root=document.getElementById("roomGame");if(!root)return;if(!room){root.innerHTML=`<div class="empty"><h2>الغرفة غير موجودة</h2><p>تأكد من كود الغرفة.</p><a class="btn" href="index.html">العودة للرئيسية</a></div>`;return}const g=getGame(room.gameId);document.getElementById("roomCode").textContent=room.code;document.getElementById("roomGameName").textContent=g.name;document.getElementById("roomPlayers").innerHTML=room.players.map(p=>`<div class="player"><span>${p.host?"👑":"👤"} ${esc(p.name)}</span>${p.host?"<small>المضيف</small>":""}</div>`).join("");document.getElementById("roomMeta").textContent=`${room.players.length} لاعب • ${g.name}`;document.getElementById("joinName").value="";renderRoomPhase(room,g)}
function joinRoom(){const room=loadRoom();if(!room)return;const input=document.getElementById("joinName"),name=(input?.value||"").trim().slice(0,20);if(!name)return alert("اكتب اسمك أولًا");if(room.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return alert("الاسم مستخدم داخل الغرفة");const max=Number((getGame(room.gameId).players.match(/\d+$/)||[8])[0]);if(room.players.length>=max)return alert("الغرفة مكتملة");room.players.push({id:id(),name,host:false});room.scores[id()]=0;updateRoom(room);renderRoom()}
function shareRoom(){const url=location.href;navigator.clipboard?.writeText(url).then(()=>alert("تم نسخ رابط الغرفة 📋")).catch(()=>prompt("انسخ رابط الغرفة:",url))}
function startGame(){const room=loadRoom();if(!room)return;if(room.players.length<2)return alert("أضف لاعبين اثنين على الأقل");room.phase="playing";room.state={round:1};updateRoom(room);renderRoom()}
function renderRoomPhase(room,g){const root=document.getElementById("roomGame");if(room.phase==="lobby"){root.innerHTML=`<div class="lobby-card"><div class="lobby-icon">${g.emoji}</div><h2>جاهزين؟</h2><p>${esc(g.desc)}</p><div class="join-row"><input id="joinName" maxlength="20" placeholder="اسم اللاعب"><button class="btn" onclick="joinRoom()">انضمام</button></div><div class="lobby-actions"><button class="btn primary" onclick="startGame()">ابدأ الجولة ▶</button><a class="btn ghost" href="game.html?id=${g.id}">شرح اللعبة</a></div><small>💡 إذا كنت على جهاز واحد، مرّر الجوال بينكم للأدوار السرية.</small></div>`;return}if(room.gameId==="spy")renderSpy(room);else if(room.gameId==="draw")renderDraw(room);else if(room.gameId==="yesno")renderYesNo(room);else if(room.gameId==="trivia")renderTrivia(room);else if(room.gameId==="would")renderWould(room);else renderCharades(room)}
function setRoomState(room,state){room.state=state;updateRoom(room);renderRoom()}
function renderSpy(room){let s=room.state||{};if(!s.word){const [cat,word]=pick(spyWords);s={round:1,cat,word,order:shuffle(room.players.map(p=>p.id)),spyId:pick(room.players.map(p=>p.id)),idx:0,revealed:null,votes:{},result:null};room.state=s;updateRoom(room)}const current=room.players.find(p=>p.id===s.order[s.idx]);const root=document.getElementById("roomGame");if(s.result){root.innerHTML=`<div class="result-card"><div class="result-emoji">${s.result.win?"🏆":"😈"}</div><h2>${esc(s.result.text)}</h2><p>الكلمة كانت: <b>${esc(s.word)}</b> — التصنيف: ${esc(s.cat)}</p><div class="scoreboard">${room.players.map(p=>`<div><span>${esc(p.name)}</span><b>${room.scores[p.id]||0}</b></div>`).join("")}</div><button class="btn primary" onclick="nextSpyRound()">جولة جديدة 🔄</button></div>`;return}if(s.revealed){root.innerHTML=`<div class="secret-card"><span>بطاقة سرية</span><h2>${esc(current.name)}</h2><div class="secret-role">${s.revealed.role==="spy"?"🕵️ أنت الجاسوس":"✅ أنت مواطن"}</div><p>${s.revealed.role==="spy"?`التصنيف فقط: <b>${esc(s.cat)}</b>`:`الكلمة السرية: <b>${esc(s.word)}</b>`}</p><button class="btn primary" onclick="hideSpyCard()">تم — سلّم الجوال ▶</button></div>`;return}if(s.idx<room.players.length){root.innerHTML=`<div class="secret-card"><div class="lobby-icon">🔐</div><h2>الدور ${s.idx+1} من ${room.players.length}</h2><p>مرّر الجوال إلى <b>${esc(current.name)}</b> فقط.</p><button class="btn primary" onclick="revealSpy()">أظهر بطاقتي 👁️</button><small>لا تسمح للاعبين الآخرين برؤية الشاشة.</small></div>`;return}renderSpyVote(room)}
function revealSpy(){const room=loadRoom(),s=room.state,pid=s.order[s.idx];const role=pid===s.spyId?"spy":"citizen";s.revealed={role};updateRoom(room);renderRoom()}
function hideSpyCard(){const room=loadRoom(),s=room.state;s.revealed=null;s.idx++;updateRoom(room);renderRoom()}
function renderSpyVote(room){const s=room.state,root=document.getElementById("roomGame");root.innerHTML=`<div class="vote-card"><span class="eyebrow">وقت النقاش</span><h2>من الجاسوس؟ 🕵️</h2><p>تحدثوا عن التلميحات ثم صوّتوا. اختاروا لاعبًا واحدًا.</p><div class="vote-grid">${room.players.map(p=>`<button class="vote-btn" onclick="voteSpy('${p.id}')">${esc(p.name)}</button>`).join("")}</div></div>`}
function voteSpy(pid){const room=loadRoom(),s=room.state,spy=room.players.find(p=>p.id===s.spyId);const caught=pid===s.spyId;if(caught){const guess=prompt("انكشف الجاسوس! خمن الكلمة السرية:");if((guess||"").trim().toLowerCase()==s.word.toLowerCase()){room.scores[s.spyId]=(room.scores[s.spyId]||0)+2;s.result={win:true,text:"الجاسوس انكشف… لكنه خمن الكلمة! 😈"}}else{room.players.filter(p=>p.id!==s.spyId).forEach(p=>room.scores[p.id]=(room.scores[p.id]||0)+1);s.result={win:true,text:`تم كشف الجاسوس ${spy.name}! 🎯`}}}else{room.scores[s.spyId]=(room.scores[s.spyId]||0)+3;s.result={win:false,text:`الجاسوس ${spy.name} أفلت منكم! 😂`}}updateRoom(room);renderRoom()}
function nextSpyRound(){const room=loadRoom();room.phase="playing";room.state={};updateRoom(room);renderRoom()}
function renderDraw(room){let s=room.state||{};if(!s.word){s={word:pick(words.draw),drawer:room.players[((room.state?.round||1)-1)%room.players.length].id,round:1,started:false,ends:0,guessed:false};room.state=s;updateRoom(room)}const drawer=room.players.find(p=>p.id===s.drawer)||room.players[0];const root=document.getElementById("roomGame");root.innerHTML=`<div class="play-card"><div class="round-head"><b>🎨 الجولة ${s.round}</b><span id="drawTimer">${s.started?Math.max(0,Math.ceil((s.ends-Date.now())/1000)):60}ث</span></div><h2>${esc(drawer.name)} يرسم</h2><canvas id="canvas" width="700" height="400"></canvas><div class="draw-tools"><button class="btn" onclick="clearCanvas()">مسح</button><input id="guessInput" maxlength="40" placeholder="اكتب تخمينك"><button class="btn primary" onclick="guessDraw()">تخمين</button></div><div class="secret-hint">🔒 الرسام يرى الكلمة فقط: <b>${esc(drawer.name)}</b> اضغط بدء إذا كنت الرسام.</div><button class="btn primary" onclick="startDraw()">ابدأ المؤقت ▶</button><p id="drawMsg" class="muted">التخمين الأسرع يأخذ نقاطًا أكثر.</p></div>`;setupCanvas()}
function setupCanvas(){const c=document.getElementById("canvas");if(!c)return;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);let drawing=false;c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointerup=()=>drawing=false;c.onpointerleave=()=>drawing=false;c.onpointermove=e=>{if(!drawing)return;ctx.lineTo(e.offsetX,e.offsetY);ctx.strokeStyle="#111827";ctx.lineWidth=5;ctx.lineCap="round";ctx.stroke()};window.__drawCtx=ctx}
function clearCanvas(){if(window.__drawCtx){window.__drawCtx.fillStyle="#fff";window.__drawCtx.fillRect(0,0,700,400)}}
function startDraw(){const room=loadRoom(),s=room.state;s.started=true;s.ends=Date.now()+60000;updateRoom(room);renderRoom();}
function guessDraw(){const room=loadRoom(),s=room.state,input=document.getElementById("guessInput"),guess=(input?.value||"").trim();if(!guess)return;if(guess.toLowerCase()===s.word.toLowerCase()){const remaining=Math.max(1,s.ends-Date.now());const pts=Math.max(1,Math.ceil(remaining/10000));const me=room.players[0];room.scores[me.id]=(room.scores[me.id]||0)+pts;room.scores[s.drawer]=(room.scores[s.drawer]||0)+1;s.guessed=true;alert(`صح! +${pts} نقطة 🎉`);s.round++;s.word=pick(words.draw);s.drawer=room.players[(s.round-1)%room.players.length].id;s.started=false;s.ends=0}else{input.value="";input.placeholder="مو هي 😅 حاول مرة ثانية"}}
function renderYesNo(room){let s=room.state||{};if(!s.prompt){s={round:1,target:room.players[0].id,prompt:pick(["هل تحب القهوة؟","هل سبق سافرت خارج السعودية؟","هل تستطيع الطبخ؟","هل تحب الألعاب؟","هل تستيقظ بدري؟","هل لديك سيارة؟"]),started:false};room.state=s;updateRoom(room)}const target=room.players.find(p=>p.id===s.target)||room.players[0];const root=document.getElementById("roomGame");root.innerHTML=`<div class="play-card"><div class="round-head"><b>🚫 الجولة ${s.round}</b><span>الهدف: ${esc(target.name)}</span></div><h2>اسألوا ${esc(target.name)} بسرعة!</h2><div class="forbidden"><span>ممنوع</span><b>نعم</b><b>لا</b></div><p>عندما يقول الهدف كلمة ممنوعة، اضغطوا الزر فورًا.</p><div class="question-box">مثال: «هل تحب القهوة؟»</div><div class="action-row"><button class="btn danger" onclick="caughtYesNo()">🚨 قال نعم/لا!</button><button class="btn primary" onclick="survivedYesNo()">نجا من الجولة 😎</button></div></div>`}
function caughtYesNo(){const room=loadRoom(),s=room.state;room.scores[s.target]=(room.scores[s.target]||0)-1;s.round++;s.target=room.players[(s.round-1)%room.players.length].id;s.prompt=pick(["هل تحب القهوة؟","هل سبق سافرت خارج السعودية؟","هل تستطيع الطبخ؟","هل تحب الألعاب؟","هل تستيقظ بدري؟"]);updateRoom(room);renderRoom()}
function survivedYesNo(){const room=loadRoom(),s=room.state;room.scores[s.target]=(room.scores[s.target]||0)+2;s.round++;s.target=room.players[(s.round-1)%room.players.length].id;s.prompt=pick(["هل تحب القهوة؟","هل سبق سافرت خارج السعودية؟","هل تستطيع الطبخ؟","هل تحب الألعاب؟","هل تستيقظ بدري؟"]);updateRoom(room);renderRoom()}
function renderTrivia(room){let s=room.state||{};if(!s.q){s={q:0,questions:shuffle(trivia).slice(0,5),answered:false};room.state=s;updateRoom(room)}const q=s.questions[s.q];if(!q){showResults(room,"انتهى تحدي المعلومات! 🧠");return}const root=document.getElementById("roomGame");root.innerHTML=`<div class="play-card"><div class="round-head"><b>🧠 السؤال ${s.q+1}/5</b><span>كل إجابة = نقاط</span></div><h2>${esc(q[0])}</h2><div class="answer-grid">${q[1].map((a,i)=>`<button class="answer" onclick="answerTrivia(${i})">${esc(a)}</button>`).join("")}</div><p class="muted">إذا كنتم على جهاز واحد، اختاروا الإجابة بالتشاور.</p></div>`}
function answerTrivia(i){const room=loadRoom(),s=room.state,q=s.questions[s.q];const correct=i===q[2];const me=room.players[0];if(correct)room.scores[me.id]=(room.scores[me.id]||0)+10;alert(correct?"إجابة صحيحة! +10 🎉":"إجابة خاطئة 😅");s.q++;updateRoom(room);renderRoom()}
function renderWould(room){let s=room.state||{};if(!s.q){s={q:0,questions:shuffle(would).slice(0,5),votes:{}};room.state=s;updateRoom(room)}if(s.q>=s.questions.length){showResults(room,"انتهت جولات لو خيروك! ⚡");return}const root=document.getElementById("roomGame");root.innerHTML=`<div class="play-card"><div class="round-head"><b>⚡ الجولة ${s.q+1}/5</b><span>صوّتوا سرًا</span></div><h2>${esc(s.questions[s.q])}</h2><div class="choice-grid"><button class="choice" onclick="chooseWould('A')">A</button><button class="choice" onclick="chooseWould('B')">B</button></div><small>بعد الاختيار، ناقشوا لماذا اخترتموه.</small></div>`}
function chooseWould(choice){const room=loadRoom(),me=room.players[0];room.scores[me.id]=(room.scores[me.id]||0)+(choice==="A"?1:0);room.state.q++;updateRoom(room);renderRoom()}
function renderCharades(room){let s=room.state||{};if(!s.word){s={word:pick(words.charades),actor:room.players[0].id,round:1,ends:0};room.state=s;updateRoom(room)}const actor=room.players.find(p=>p.id===s.actor)||room.players[0];const root=document.getElementById("roomGame");root.innerHTML=`<div class="play-card"><div class="round-head"><b>🎭 الجولة ${s.round}</b><span id="charTimer">60ث</span></div><h2>${esc(actor.name)} يمثل</h2><div class="actor-secret">🤫 الممثل فقط ينظر هنا<br><strong>${esc(s.word)}</strong></div><div class="action-row"><button class="btn primary" onclick="startCharades()">ابدأ الدقيقة ▶</button><button class="btn" onclick="charadesSolved()">عرفناها! 🎉</button></div><p class="muted">ممنوع الكلام أو تهجئة الكلمة.</p></div>`}
function startCharades(){const room=loadRoom();room.state.ends=Date.now()+60000;updateRoom(room);renderRoom();setTimeout(()=>renderRoom(),60000)}
function charadesSolved(){const room=loadRoom(),s=room.state;room.scores[s.actor]=(room.scores[s.actor]||0)+2;s.round++;s.actor=room.players[(s.round-1)%room.players.length].id;s.word=pick(words.charades);s.ends=0;updateRoom(room);renderRoom()}
function showResults(room,title){const root=document.getElementById("roomGame");const ranked=[...room.players].sort((a,b)=>(room.scores[b.id]||0)-(room.scores[a.id]||0));root.innerHTML=`<div class="result-card"><div class="result-emoji">🏆</div><h2>${title}</h2><div class="scoreboard">${ranked.map((p,i)=>`<div><span>${i===0?"🥇":"👤"} ${esc(p.name)}</span><b>${room.scores[p.id]||0}</b></div>`).join("")}</div><button class="btn primary" onclick="location.href='index.html'">العودة للرئيسية</button></div>`}
function startFromQuery(){renderGames();renderGame();if(location.pathname.endsWith("room.html"))renderRoom()}
startFromQuery();

/* Demo admin only — replace with real server-side auth before public production. */
function adminLogin(){
  const e=(document.getElementById("email")?.value||"").trim();
  const p=document.getElementById("password")?.value||"";
  if(e==="admin@l3btna.local"&&p==="L3btna@2026!"){sessionStorage.setItem("la3bak_admin_demo","1");initAdmin()}else alert("بيانات الدخول غير صحيحة")
}
function logout(){sessionStorage.removeItem("la3bak_admin_demo");location.reload()}
function initAdmin(){document.getElementById("login")?.classList.add("hidden");document.getElementById("sidebar")?.classList.remove("hidden");document.getElementById("dashboard")?.classList.remove("hidden");renderAdmin()}
function renderAdmin(){
  const d=getData();
  const sales=(d.orders||[]).reduce((a,o)=>a+Number(o.amount||0),0);
  const set=(id,v)=>{const x=document.getElementById(id);if(x)x.textContent=v};
  set("sales",sales+" ر.س");set("purchases",(d.orders||[]).length);set("gameCount",games.length);set("roomCount",(d.rooms||[]).length);
  const ag=document.getElementById("adminGames");if(ag)ag.innerHTML=games.map(g=>`<div class="admin-row"><span>${g.emoji} <b>${esc(g.name)}</b><small>${g.price} ريال • ${esc(g.players)}</small></span><span class="muted">جاهزة</span></div>`).join("");
  const ol=document.getElementById("ordersList");if(ol)ol.innerHTML=(d.orders||[]).length?(d.orders||[]).slice().reverse().map(o=>`<div class="admin-row"><span>${esc(o.game||"لعبة")}<small>${esc(o.date||"")}</small></span><b>${Number(o.amount||0)} ر.س</b></div>`).join(""):"<p class=muted>لا توجد مشتريات حقيقية؛ الدفع غير مربوط بعد.</p>";
  const rl=document.getElementById("roomsList");if(rl)rl.innerHTML=(d.rooms||[]).length?(d.rooms||[]).slice().reverse().map(r=>`<div class="admin-row"><span>🔗 ${esc(r.code)}<small>${esc(getGame(r.gameId).name)}</small></span><b>${(r.players||[]).length} لاعبين</b></div>`).join(""):"<p class=muted>لا توجد غرف بعد.</p>";
}
function showAddGame(){alert("الألعاب الأساسية مدمجة داخل النظام. تعديلها من هذه النسخة التجريبية غير متاح حتى نربط لوحة الإدارة بقاعدة بيانات آمنة.")}
function editGame(){showAddGame()}
function closeModal(){document.getElementById("modal")?.classList.add("hidden")}
function saveGame(){showAddGame()}
if(location.pathname.endsWith("admin.html")&&sessionStorage.getItem("la3bak_admin_demo")==="1")initAdmin();
